Dev
ITUBIDB/cavabunga pull request #30
Opened 2018-04-16 07:49 UTC by dgkncelik

2018-04-16 09:55 UTC, karakayasemi commented
what is missing in here?

2018-04-21 21:44 UTC, karakayasemi requested changes
The code looks okay for me after reviewed small changes, how can I test and see output HTML?

2018-04-21 21:44 UTC, karakayasemi commented on src/main/java/edu/itu/cavabunga/business/CalendarManagerServiceImpl.java
> +        if(participantService.getAllParticipant().isEmpty()){
no need to this addition in here

2018-04-21 21:44 UTC, karakayasemi commented on src/main/java/edu/itu/cavabunga/controller/ComponentController.java
> +            @ApiResponse(code = 404, message = "No Wcomponent found with id = {component_id}", response = ErrorResponse.class),
typo

2018-04-21 21:44 UTC, karakayasemi commented on src/main/java/edu/itu/cavabunga/controller/ParticipantController.java
> +            @ApiResponse(code = 404, message = "No partipants found", response = ErrorResponse.class),
pls remove

2018-04-21 21:44 UTC, karakayasemi commented on src/main/java/edu/itu/cavabunga/controller/PropertyController.java
> +            @ApiResponse(code = 200, message = "Succefully retrieve parameters of property with id = {property_id}", response = ParameterResponse.class),
typo

2018-04-24 10:53 UTC, karakayasemi requested changes

2018-04-24 10:53 UTC, karakayasemi commented on src/main/resources/application.properties
> -spring.datasource.url=jdbc:mysql://127.0.0.1/test
revert

2018-04-24 11:00 UTC, karakayasemi commented
@gitmate rebase

2018-04-24 11:14 UTC, karakayasemi commented
@gitmate-bot rebase

2018-04-24 11:16 UTC, karakayasemi commented
@gitmate-bot rebase

2018-04-24 11:30 UTC, karakayasemi commented
@gitmate-bot rebase

2018-04-24 11:30 UTC, itudevops commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-04-24 11:30 UTC, itudevops commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-04-24 11:33 UTC, karakayasemi commented
@dgkncelik please squash your last 2 commits, they are irrelevant for development tree.

2018-04-24 11:58 UTC, karakayasemi approved these changes

2018-04-24 11:58 UTC, merged